dist: bionic
language: python
python: 3.8

addons:
  apt:
    packages:
      - chrpath

branches:
  except:
  - /^v.*$/

install:
  - pip install caos~=2.0

script:
  - caos init
  - ln -s $(which pip) venv/bin/pip # This is a hack for Travis CI that adds the missing pip binary
  - caos update
  - caos run build
  - export PYGMYPYTHON_VERSION="v$(python -c 'from src.python.pygmypython import __version__; print(__version__)')"
  - export PYGMYPYTHON_ZIP="pygmypython-$PYGMYPYTHON_VERSION.zip"
  - mv dist/pygmypython dist/pygmypython-$PYGMYPYTHON_VERSION
  # Entering into the dist folder is required so that the generated zip does not add the dist folder
  - ( echo "Creating '$PYGMYPYTHON_ZIP'..."
      && cd dist
      && zip -qr $PYGMYPYTHON_ZIP pygmypython-$PYGMYPYTHON_VERSION
    ) || (echo "ERROR. Could not create zip file" && exit 1)

before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "builds@travis-ci.com"
  - export PYGMYPYTHON_VERSION="v$(python -c 'from src.python.pygmypython import __version__; print(__version__)')" && echo "Tag '$PYGMYPYTHON_VERSION'"
  - ((git tag -d $PYGMYPYTHON_VERSION) && echo "Local Tag Deleted") || echo "Nothing to do"
  - ((git push --delete https://$GITHUB_OAUTH_TOKEN@github.com/caotic-co/Pygmy-Python.git $PYGMYPYTHON_VERSION) && echo "Remote Tag Deleted") || echo "Nothing to do"
  -  git tag $PYGMYPYTHON_VERSION -a -m "Generated tag '$PYGMYPYTHON_VERSION' from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: dist/pygmypython-$PYGMYPYTHON_VERSION.zip
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: false

