language: python
python: 3.8

install:
  - pip install -U pip
  - pip install -U virtualenv
  - pip install -U wheel
  - pip install caos~=2.0

script:
  - caos init
  - caos update
  - caos run tests
  - caos run build
