language: python
python: 3.8

addons:
  apt:
    packages:
      - chrpath


install:
  - pip install caos~=2.0


script:
  - caos init
  - ln -s $(which pip) venv/bin/pip # This is a hack for Travis CI that adds the missing pip binary
  - caos update
  - caos run tests
  - caos run build


before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "builds@travis-ci.com"
  - cd .. && export GIT_TAG="v$(python -c 'from pygmypython_core import __version__; print(__version__)')"
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUB_OAUTH_TOKEN@github.com/caotic-co/Pygmy-Python.git --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "pygmypython/**/*"
  on:
    branch: master
    tags: false

