dist: bionic
language: python
python: 3.8

addons:
  apt:
    packages:
      - chrpath


branches:
  except:
  - /^v.*$/

install:
  - pip install caos~=2.0


script:
  - caos init
  - ln -s $(which pip) venv/bin/pip # This is a hack for Travis CI that adds the missing pip binary
  - caos update
  - caos run tests
  - caos run build
  - export PYGMYPYTHON_ZIP="pygmypython-v$(python -c 'from pygmypython_core import __version__; print(__version__)').zip"
  - echo "Creating '$PYGMYPYTHON_ZIP'..." && ((zip -r dist/$PYGMYPYTHON_ZIP dist/pygmypython) || echo "ERROR. Could not create zip file")


before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "builds@travis-ci.com"
  - export GIT_TAG="v$(python -c 'from pygmypython_core import __version__; print(__version__)')" && echo "Tag '$GIT_TAG'"
  - ((git tag -d $GIT_TAG) && echo "Local Tag Deleted") || echo "Nothing to do"
  - ((git push --delete https://$GITHUB_OAUTH_TOKEN@github.com/caotic-co/Pygmy-Python.git $GIT_TAG) && echo "Remote Tag Deleted") || echo "Nothing to do"
  -  git tag $GIT_TAG -a -m "Generated tag '$GIT_TAG' from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: dist/pygmypython-v*.zip
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: false

