dist: bionic
language: python
python: 3.8

addons:
  apt:
    packages:
      - chrpath

install:
  - pip install caos~=2.0

script:
  - caos init && ln -s $(which pip) venv/bin/pip
  - caos update
  - caos run tests
  - caos run build
