dist: bionic
language: minimal
python: 3.8

install:
  - pip3.8 install caos~=2.0

script:
  - python3.8 -c "print('3.8')"
  - python3 -c "print('3')"
  - caos init
  - caos update
  - caos run tests
  - caos run build
