language: python
python: 3.8

install:
  - pip install caos~=2.0

script:
  - (mv ~/.pydistutils.cfg ~/oldpydistutils.cfg) || exit 0
  - caos init
  - caos update
  - caos run tests
  - caos run build
