language: python
python: 3.8

addons:
  apt:
    packages:
      - chrpath

install:
  - pip install caos~=2.0

script:
  - caos init
  - ln -s $(which pip) venv/bin/pip # This is a hack for Travis CI that adds the missing pip binary
  - caos update
  - caos run tests
  - caos run build
  - echo "$(pwd)"
  - echo "$TRAVIS_BUILD_DIR"
  - echo "$(ls -l)"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "dist/**/*"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true

